config/routes.rb
Meritorious::Application.routes.draw do
  devise_for :teachers
  root to: 'high_voltage/pages#show', id: 'home'

  resources :classrooms, only: [:index, :show, :new, :create] do
    resources :meetings, only: [:index]
    resource :student_imports, only: [:create]
  end
  resources :meetings, only: [:show, :create] do
    resources :marks, only: [:create]
    resource :meeting_report_exports, only: [:create]
  end
end

app/models/class_assignment.rb
class ClassAssignment < ActiveRecord::Base
  belongs_to :student
  belongs_to :classroom
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :school
  belongs_to :teacher

  has_many :class_assignments
  has_many :students, through: :class_assignments
  has_many :meetings
  has_many :marks, through: :meetings

  validates :name, presence: true
end

app/models/demerit.rb
class Demerit < ActiveRecord::Base
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
  belongs_to :meeting
  belongs_to :content, polymorphic: true
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  include Schizo::Data

  belongs_to :classroom

  has_many :marks

  def start_time
    created_at.in_time_zone
  end
end

app/models/merit.rb
class Merit < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :teachers
  has_many :students
  has_many :classrooms

  validates :name, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  include Schizo::Data

  belongs_to :school

  has_many :class_assignments
  has_many :classrooms, through: :class_assignments

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :student_id, presence: { message: :blank },
                         uniqueness: { scope: :school_id,
                                       message: :unique
                                     }

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  include Schizo::Data

  has_many :classrooms
  has_many :students, through: :classrooms
  has_many :meetings, through: :classrooms
  belongs_to :school

  validates :first_name, presence: true
  validates :last_name, presence: true

  devise(:database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
        )

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_teacher!
end

app/controllers/classrooms_controller.rb
class ClassroomsController < AuthenticatedController
  respond_to :js, only: [:new]

  def index
    @classrooms = current_teacher.classrooms
  end

  def show
    @classroom = find_classroom
    @students = @classroom.students
  end

  def new
    @classroom = current_teacher.classrooms.build
  end

  def create
    @classroom = current_teacher.classrooms.build(classroom_params)
    if @classroom.save
      flash[:success] = 'Classroom created successfully'
    else
      flash[:failure] = 'Could not create classroom'
    end
    redirect_to classrooms_path
  end

  private

  def find_classroom
    current_teacher.classrooms.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:name)
  end
end

app/controllers/marks_controller.rb
class MarksController < AuthenticatedController
  respond_to :js

  def create
    AssigningMarks.new(current_teacher, find_student).assign(build_mark)
    @student = Reporting.new(find_meeting).data(:student_meeting, find_student)
  end

  private

  def find_meeting
    Meeting.find_by_id(params[:meeting_id])
  end

  def find_student
    Student.find_by_id(params[:student_id])
  end

  def build_mark
    CreatingMarks.new(current_teacher, find_meeting).create(mark_params)
  end

  def mark_params
    params.require(:mark).permit(:type)
  end
end

app/controllers/meeting_report_exports_controller.rb
class MeetingReportExportsController < AuthenticatedController
  def create
    meeting = current_teacher.meetings.find(params[:meeting_id])
    report = Reporting.new(meeting)
    @data = report.csv_data(:meeting)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < AuthenticatedController
  def index
    @meetings = find_classroom.meetings
  end

  def create
    @meeting = Meeting.create(classroom: find_classroom)
    redirect_to meeting_path(@meeting)
  end

  def show
    @meeting = MeetingPresenter.new(find_meeting)
  end

  private

  def find_classroom
    current_teacher.classrooms.find(params[:classroom_id])
  end

  def find_meeting
    current_teacher.meetings.find(params[:id])
  end
end

app/controllers/student_imports_controller.rb
class StudentImportsController < AuthenticatedController
  def create
    @classroom = current_teacher.classrooms.find(params[:classroom_id])
    @errors = ImportingStudents.new(params[:student_imports], @classroom).import
    if @errors.empty?
      flash[:success] = 'Students successfully imported'
      redirect_to classroom_path(params[:classroom_id])
    else
      @students = @classroom.students
      flash[:notice] = 'There were errors in the import'
      render 'classrooms/show'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_main_nav.html.erb
<ul class='signed-in'>
  <li id='title'><%= link_to 'meritorious', root_path %></li>
  <li><%= link_to 'Classrooms', classrooms_path %></li>
  <li id='session'>
    <%= link_to 'Sign Out', destroy_teacher_session_path, method: :delete %>
  </li>
</ul>

app/views/application/_nav.html.erb
<nav class='main'>
  <% if current_teacher %>
    <%= render 'main_nav' %>
  <% else %>
    <%= render 'signed_out_nav' %>
  <% end %>
  <div class='clearfix'>
</nav>

app/views/application/_signed_out_nav.html.erb
<ul class='signed-out'>
  <li id='title'><%= link_to 'meritorious', root_path %></li>
  <li id='session'><%= link_to 'Sign In', new_teacher_session_path %></li>
</ul>

app/views/classrooms/_classroom.html.erb
<li data-role='classroom-<%= classroom.id %>'>
  <%= link_to classroom.name, classroom_path(classroom) %>
  <span class='new-meeting'><%= button_to 'Start Class', meetings_path(classroom_id: classroom.id) %></span>
</li>

app/views/classrooms/_new.js.erb
<%= simple_form_for classroom do |form| %>
  <%= form.input :name %>
  <%= form.submit %>
<% end %>

app/views/classrooms/_student.html.erb
<li>
  <div data-role='student'>
    <p><%= student.name %></p>
  </div>
</li>

app/views/classrooms/index.html.erb
<main id='classrooms'>
  <header>
    <h1>Classrooms for <%= current_teacher.name %></h1>
  </header>

  <section id='new-classroom'>
    <%= link_to 'Create Classroom', new_classroom_path, remote: true %>
    <div id='new-classroom-form'></div>
  </section>

  <ul id='classroom-list'>
    <% @classrooms.each do |classroom| %>
      <%= render 'classroom', classroom: classroom %>
    <% end %>
  </ul>
</main>

app/views/classrooms/new.js.erb
$('#new-classroom-form').html("<%= escape_javascript(render('new', classroom: @classroom)) %>");

app/views/classrooms/show.html.erb
<main id='classroom'>
  <header>
    <h1><%= @classroom.name %></h1>
    <h2 data-role='meeting-list'><%= link_to 'Past Meetings', classroom_meetings_path(@classroom) %></h2>
  </header>

  <div id='students-import'>
    <%= form_tag classroom_student_imports_path(@classroom), multipart: true,  method: :post do %>
      <%= file_field_tag 'student_imports' %>
      <%= submit_tag 'Import Students' %>
    <% end %>

    <% if @errors %>
      <%= render 'student_imports/import_errors', errors: @errors %>
    <% end %>
  </div>

  <ul id='students-list'>
    <% @students.each do |student| %>
      <%= render 'classrooms/student', student: student %>
    <% end %>
  </ul>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'nav' %>
  <%= render 'flashes' -%>
  <%= yield %>
  <%= render 'javascript' %>
</body>
</html>

app/views/marks/create.js.erb
$('[data-role="student-<%= @student.id %>"] .merits-count').text("<%= @student.merits_count %>");
$('[data-role="student-<%= @student.id %>"] .demerits-count').text("<%= @student.demerits_count %>");

app/views/meeting_report_exports/create.csv.erb
<%= @data.headers.join(',') %>
<% @data.each do |row| %>
  <%= row.join(',') %>
<% end %>

app/views/meetings/_student.html.erb
<li data-role='student-<%= student.id %>'>
  <div class='name'><%= student.name %></div>
  <section class='marks'>
    <div class='add-merit'>
      <%= link_to '+',
                  meeting_marks_path(meeting,
                                     mark: { type: :merit },
                                     student_id: student.id
                                    ),
                  remote: true,
                  method: :post
      %>
    </div>
    <p class='merits-count'>0</p>
  </section>
  <section class='marks'>
    <div class='add-demerit'>
      <%= link_to '-',
                  meeting_marks_path(meeting,
                                     mark: { type: :demerit },
                                     student_id: student.id
                                    ),
                  remote: true,
                  method: :post
      %>
    </div>
    <p class='demerits-count'>0</p>
  </section>
</li>

app/views/meetings/index.html.erb
<main id='meeting-list'>
  <header>
    <h1>List of Meetings</h1>
  </header>
  <ul>
    <% @meetings.each do |meeting| %>
      <li><%= link_to l(meeting.created_at, format: :day_time), meeting_path(meeting) %></li>
    <% end %>
  </ul>
</main>

app/views/meetings/show.html.erb
<main id='meeting'>
  <header>
    <h1><%= @meeting.name %></h1>
    <h2><%= @meeting.start_time %></h2>
  </header>
  <div id='end-class'><%= link_to 'End Class', classrooms_path %></div>
  <div id='export-report'><%= button_to 'Export Meeting Report', meeting_meeting_report_exports_path(@meeting, format: :csv) %>
  <section id='students-list'>
    <ul>
      <% @meeting.students.each do |student| %>
        <%= render 'student', student: student, meeting: @meeting %>
      <% end %>
    </ul>
  </section>
</main>

app/views/pages/home.html.erb
<main class='home'>
  <h1>meritorious</h1>
  <p>
    Computer, lights up! I am your worst nightmare! Fate.
    It protects fools, little children, and ships named "Enterprise."
    Some days you get the bear, and some days the bear gets you. This should be interesting.
    Smooth as an android's bottom, eh, Data?
    For an android with no feelings, he sure managed to evoke them in others.
    We have a saboteur aboard. This is not about revenge. This is about justice.
    Damage report! My oath is between Captain Kargan and myself.
    Your only concern is with how you obey my orders.
    Or do you prefer the rank of prisoner to that of lieutenant?
    Fate protects fools, little children and ships named Enterprise.
    What's a knock-out like you doing in a computer-generated gin joint like this?
    Now, how the hell do we defeat an enemy that knows us better than we know ourselves?
    I'll alert the crew. I'm afraid I still don't understand, sir. I will obey your orders.
    I will serve this ship as First Officer. And in an attack against the Enterprise, I will die with this crew.
    But I will not break my oath of loyalty to Starfleet. Your shields were failing, sir.
  </p>
</main>

app/views/student_imports/_import_errors.html.erb
<ul id='import-errors'>
  <% errors.each do |student, messages| %>
    <% messages.each do |message| %>
      <li><%= student %>: <%= message %></li>
    <% end %>
  <% end %>
</ul>